services:

  mysql:
    image: mysql:8.0
    container_name: inventory-mysql
    restart: unless-stopped
    networks:
      - inventory-network
    env_file:
      - ./.env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3307:3306'
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: inventory-backend
    restart: unless-stopped
    networks:
      - inventory-network
    working_dir: /var/www/html/backend
    volumes:
      - ./backend:/var/www/html/backend
      - backend_vendor:/var/www/html/backend/vendor
    depends_on:
      - mysql
    ports:
      - '9090:9090'
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: inventory-frontend
    restart: unless-stopped
    networks:
      - inventory-network
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    ports:
      - '3090:3090'
    env_file:
      - ./frontend/.env

volumes:
  mysql_data:
  backend_vendor:
  frontend_node_modules:

networks:
  inventory-network:
    driver: bridge